language: python
python:
  - "2.7"
env:
  - TOX_ENV=py27
  - TOX_ENV=static_check
install:
  - pip install tox coverage
script:
  - tox -e $TOX_ENV

after_success:
  - bash <(curl -s https://codecov.io/bash) -f '!./tests/*'
