language: python
python:
- '2.7'
env:
- TOX_ENV=py27
- TOX_ENV=static_check
install:
- pip install tox coverage
script:
- tox -e $TOX_ENV
after_success:
- bash <(curl -s https://codecov.io/bash) -f '!./tests/*'
deploy:
  provider: pypi
  user: 1tush
  password:
    secure: TCCfFw2Qx+QiyNtk5bM8kJtu+/WwaoO51jIWu38kFhziIwUnJptiHa35mt5nU0srQom7fiMHCZT4ShiFlegNuDl6ccQt92EpRhpyEHuR72BkM2zSYVC5MkFWCEx3VdpcIOXeDjItr62yhd3wfc6EVngjYOsPC1er2xgSRF+LYXKjNQK0CGlYDkKzZ0V+Cyj4DiXUUpaeNEMKuyjaME7Zcpyc8zX1ju04ocB00ig/jQ6M6/xZwoylUu9XksxjHPaamEVZP1ijXDPKPQxFJbHzdLQDE7IL9sMor10pUpmTt/ksGaweHcGnDUOmp4cKWQ8zBjWRUK8LrByyf4ohsdgBnmaTzgYnHBoxdzPYK+04o2ovvvxRBZ3E2bk8YRxLl0YCpHnCZgfqlsjmnW1mxDk3KPu6BKfNaRt+M2IofHgCyDf9gQxNvNGaXvGuDEFsgGMlgMULz8eGXG+AcK5DDe1NMfrf5GM6PHW0DQJMs97NSyfcwM9i2a/1PQdgMQ+O/uMQ7Q+q89SuJid5pj3mdyAPFabPT7aEstGaW4rjeLc8AnVnEKn58Uqc4Fhnh2JwpkGscdgzgWu+Pr5daaCUcR45gAHT1pbfhZpiOEp2UzA8wX77TffWXszfyAomJdrrgfJnRg93G1vHu7CAkyzZERbeg5WpulXrjfsht1sKR4hRuYU=
  on:
    tags: true
